### ISSUE TITLE
Out of Memory Error with GrowingSphere

### ISSUE THREAD

**Issue by Grahams-Uncle** [BirkhoffG/ReLax#163]
GrowingSphere has error when running on road dataset

```sh
(relax) chuck@gpu-v100-1:~/ReLax$ python -m scripts.benchmark --data_name road --cf_methods GrowingSphere
start...
CF method(s):  GrowingSphere
Dataset(s):  ['road']
/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
generate...
2023-05-17 23:07:34.382193: W external/tsl/tsl/framework/bfc_allocator.cc:296] Allocator (GPU_0_bfc) ran out of memory trying to allocate 5.22GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
Traceback (most recent call last):
  File "/home/chuck/ReLax/scripts/benchmark.py", line 105, in <module>
    main(args)
  File "/home/chuck/ReLax/scripts/benchmark.py", line 65, in main
    cf_exp = generate_cf_explanations(cf, dm, pred_fn=pred_fn, pred_fn_args=dict(params=params, rng_key=jrand.PRNGKey(0)), strategy = strategy)
  File "/home/chuck/ReLax/relax/evaluate.py", line 258, in generate_cf_explanations
    cfs = strategy(cf_module.generate_cf, X, pred_fn=pred_fn)
  File "/home/chuck/ReLax/relax/evaluate.py", line 91, in __call__
    cfs = jax.vmap(partial_fn)(X)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/api.py", line 1239, in vmap_f
    out_flat = batching.batch(
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/chuck/ReLax/relax/methods/sphere.py", line 164, in generate_cf
    cf = _growing_spheres(
  File "/home/chuck/ReLax/relax/utils.py", line 123, in wrapper
    cf = func(**kwargs)
  File "/home/chuck/ReLax/relax/methods/sphere.py", line 123, in _growing_spheres
    candidate_cf, _, _ = lax.fori_loop(0, n_steps, step, state)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1768, in fori_loop
    (_, result), _ = scan(_fori_scan_body_fun(body_fun), (lower_, init_val),
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 262, in scan
    out = scan_p.bind(*consts, *in_flat,
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1031, in scan_bind
    return core.AxisPrimitive.bind(scan_p, *args, **params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/core.py", line 2633, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/interpreters/batching.py", line 363, in process_primitive
    val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 809, in _scan_batching_rule
    outs = scan_p.bind(
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1031, in scan_bind
    return core.AxisPrimitive.bind(scan_p, *args, **params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/core.py", line 2633, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/dispatch.py", line 131, in apply_primitive
    compiled_fun = xla_primitive_callable(
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/util.py", line 284, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/util.py", line 277, in cached
    return f(*args, **kwargs)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/dispatch.py", line 222, in xla_primitive_callable
    compiled = _xla_callable_uncached(
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/dispatch.py", line 252, in _xla_callable_uncached
    return computation.compile().unsafe_call
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 2313, in compile
    executable = UnloadedMeshExecutable.from_hlo(
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 2633, in from_hlo
    xla_executable, compile_options = _cached_compilation(
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 2551, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/dispatch.py", line 495, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/dispatch.py", line 463, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 5604977216 bytes.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/chuck/ReLax/scripts/benchmark.py", line 105, in <module>
    main(args)
  File "/home/chuck/ReLax/scripts/benchmark.py", line 65, in main
    cf_exp = generate_cf_explanations(cf, dm, pred_fn=pred_fn, pred_fn_args=dict(params=params, rng_key=jrand.PRNGKey(0)), strategy = strategy)
  File "/home/chuck/ReLax/relax/evaluate.py", line 258, in generate_cf_explanations
    cfs = strategy(cf_module.generate_cf, X, pred_fn=pred_fn)
  File "/home/chuck/ReLax/relax/evaluate.py", line 91, in __call__
    cfs = jax.vmap(partial_fn)(X)
  File "/home/chuck/ReLax/relax/methods/sphere.py", line 164, in generate_cf
    cf = _growing_spheres(
  File "/home/chuck/ReLax/relax/utils.py", line 123, in wrapper
    cf = func(**kwargs)
  File "/home/chuck/ReLax/relax/methods/sphere.py", line 123, in _growing_spheres
    candidate_cf, _, _ = lax.fori_loop(0, n_steps, step, state)
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 5604977216 bytes.
'''

**Comment by BirkhoffG** [comment]
Do you receive OOM error when running the first step in Sphere?
