### ISSUE TITLE
Issues on gpu-v100-4

### ISSUE THREAD

**Issue by Grahams-Uncle** [BirkhoffG/ReLax#177]
```sh
(relax) chuck@gpu-v100-4:~/ReLax$ python -m scripts.benchamrk_large_dataset --cf_methods all --strategy pmap  --to_csv True --csv_name forktable_pmap
start...
CF method(s):  ['VanillaCF', 'DiverseCF', 'ProtoCF', 'CounterNet', 'CCHVAE', 'CLUE', 'GrowingSphere', 'VAECF']
Downloading readme: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 989/989 [00:00<00:00, 1.54MB/s]
Downloading and preparing dataset None/None to /home/chuck/.cache/huggingface/datasets/birkhoffg___parquet/birkhoffg--folktables-acs-income-bc190711a423bf3e/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec...
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 74.0M/74.0M [00:01<00:00, 57.3MB/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 74.0M/74.0M [00:01<00:00, 61.5MB/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49.3M/49.3M [00:00<00:00, 53.9MB/s]
Downloading data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.61s/it]
Extracting data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1427.12it/s]
Dataset parquet downloaded and prepared to /home/chuck/.cache/huggingface/datasets/birkhoffg___parquet/birkhoffg--folktables-acs-income-bc190711a423bf3e/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec. Subsequent calls will reuse this data.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  5.28it/s]
df is loaded
/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
Benchmarking CF method: VanillaCF
generate...
2023-05-24 02:00:37.091249: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:427] Loaded runtime CuDNN library: 8.5.0 but source was compiled with: 8.8.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Traceback (most recent call last):
  File "/home/chuck/ReLax/scripts/benchamrk_large_dataset.py", line 181, in <module>
    main(args)
  File "/home/chuck/ReLax/scripts/benchamrk_large_dataset.py", line 145, in main
    cf_exp = generate_cf_explanations(cf, dm, pred_fn=pred_fn, pred_fn_args=dict(params=params, rng_key=jrand.PRNGKey(0)), strategy=strategy)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/random.py", line 137, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/prng.py", line 320, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/prng.py", line 732, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/prng.py", line 744, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/prng.py", line 749, in random_seed_impl_base
    return seed(seeds)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/prng.py", line 978, in threefry_seed
    return _threefry_seed(seed)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/pjit.py", line 208, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/pjit.py", line 155, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/core.py", line 2633, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/pjit.py", line 1088, in _pjit_call_impl
    always_lower=False, lowering_platform=None).compile()
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 2313, in compile
    executable = UnloadedMeshExecutable.from_hlo(
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 2633, in from_hlo
    xla_executable, compile_options = _cached_compilation(
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 2551, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/dispatch.py", line 494, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/dispatch.py", line 462, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/chuck/ReLax/scripts/benchamrk_large_dataset.py", line 181, in <module>
    main(args)
  File "/home/chuck/ReLax/scripts/benchamrk_large_dataset.py", line 145, in main
    cf_exp = generate_cf_explanations(cf, dm, pred_fn=pred_fn, pred_fn_args=dict(params=params, rng_key=jrand.PRNGKey(0)), strategy=strategy)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/random.py", line 137, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/prng.py", line 320, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/prng.py", line 732, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/prng.py", line 744, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/prng.py", line 749, in random_seed_impl_base
    return seed(seeds)
  File "/home/chuck/mambaforge-pypy3/envs/relax/lib/python3.10/site-packages/jax/_src/prng.py", line 978, in threefry_seed
    return _threefry_seed(seed)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

**Comment by BirkhoffG** [comment]
Can you run the same script on those mid-sized data? 

From the message, it seems to be the problem with the JAX installation.
